apiVersion: v1
kind: Pod
metadata:
  name: box
spec:
  containers:
  - name: box
    image: kennethreitz/pipenv
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
