apiVersion: v1
kind: ConfigMap
metadata:
  name: signing
data:
  secret-key: cards-amusing-humanity
  token-ttl-hours: "1"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics
data:
  database-name: analytics
  database-user: postgresadmin
  database-password: admin123
