# Entire application config split by intended service.
# These configmaps can be used by other services when convenient.

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: signing
data:
  secret-key: cards-amusing-humanity
  token-ttl-hours: "1"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics
data:
  postgres-name: analytics
  postgres-user: postgresadmin
  postgres-password: admin123

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cards
data:
  postgres-name: cards
  postgres-user: postgresadmin
  postgres-password: admin123
  default_num_answers: '5'

---


  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: gateway
  data:
    rate-limiting-threshold: '200'
    blocked-ip-timeout: '60'

---
