apiVersion: skaffold/v1beta7
kind: Config
build:
  local: {}
  artifacts:
  - image: cah-analytics
    context: analytics
  - image: cah-signing
    context: signing
deploy:
  kubectl:
    manifests:
      - "*/manifest.yaml"
