apiVersion: skaffold/v1beta7
kind: Config
build:
  local: {}
  artifacts:
  - image: cah-analytics
    context: analytics
    sync:
      "*.py": .
  - image: cah-cards
    context: cards
    sync:
      "*.py": .
  - image: cah-signing
    context: signing
    sync:
      "*.py": .
  - image: cah-website
    context: website
deploy:
  kubectl:
    manifests:
      - "config.yaml"
      - "*/manifest.yaml"
