openapi: 3.0.0
info:
  title: Shared Types
  version: 1.0.0
components:
  schemas:
    Error:
      type: object
      required:
      - error
      properties:
        error:
          type: string
    Game:
      type: object
      required:
      - token
      properties:
        choice:
          type: string
        token:
          type: string
    Result:
      type: object
      required:
      - similarity
      properties:
        similarity:
          type: number
          minimum: 0
          maximum: 1
    Token:
      type: object
      required:
      - token
      properties:
        token:
          type: string
    Payload:
      type: object
      required:
      - payload
      properties:
        payload:
          type: object
