openapi: 3.0.0
info:
  version: 1.0.0
  title: Gateway Service
  description: A service acting as a gate to prevent attacks.
paths:
  /game:
    get:
      description: Returns a brand new game.
      operationId: Start Game.
      parameters:
        - in: query
          name: deck
          schema:
            type: string
          description: Optional parameter specify a type of deck (e.g. nsfw)
      responses:
        '200':
          description: Return a brand new game with new random cards.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../types.yaml#/components/schemas/Game'
        "404":
          description: Resource not found, error return in case of attack.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '../types.yaml#/components/schemas/Error'
  /submit:
    post:
      description: Submit a game outcome.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../types.yaml#/components/schemas/Game"
      responses:
        "200":
          description: Successful handling.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Result"
        "401":
          description: Expired or malformed token.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "403":
          description: Duplicate game submission.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "500":
          description: Internal Error.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
