# Service to expose Cards deployment.
apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

---

# Cards service deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
      - name: cards
        image: cah-cards
        env:
        - name: FLASK_DEBUG
          value: "1"
        - name: TOKEN_TTL_HOURS
          valueFrom:
            configMapKeyRef:
              name: signing
              key: token-ttl-hours
        - name: DEFAULT_NUM_ANSWERS
          valueFrom:
            configMapKeyRef:
              name: cards
              key: default_num_answers
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: cards
              key: postgres-name
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: cards
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: cards
              key: postgres-password
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 2

---

# Service to expose cards' Postgres deployment.
apiVersion: v1
kind: Service
metadata:
  name: cards-postgres
spec:
  selector:
    app: cards-postgres
  ports:
  - protocol: TCP
    port: 5432

---

# Cards service's Postgres deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-postgres
  template:
    metadata:
      labels:
        app: cards-postgres
    spec:
      containers:
      - name: cards-postgres
        image: postgres:11
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: cards
              key: postgres-name
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: cards
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: cards
              key: postgres-password