openapi: 3.0.0
info:
  version: 1.0.0
  title: Cards Service
  description: A card services in the game cards against humanity with OpenAPI 3.0 specification
paths:
  /game:
    get:
      description: Returns a new game and different game at each call
      operationId: Get a new game.
      parameters:
        - in: query
          name: deck
          schema:
            type: string
          description: Optional parameter specify a type of deck (e.g. nsfw)
      responses:
        "200":
          description: Successful handling.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Game"
        "404":
          description: Can't find resources
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
