openapi: "3.0.0"
info:
  version: 1.0.0
  title: Cards Service
  description: A card services in the game cards against humanity with OpenAPI 3.0 specification
paths:
  /game:
    get:
      description: |
        Returns a new game and different game at each call
      operationId: Get a new game.
      parameters:
        - in: query
          name: token
          schema:
            type: string
          description: The token provided with the game
        - in: query
          name: deck
          schema:
            type: string
          description: Optional parameter specify a type of deck (e.g. NSFW)
      responses:
        "200":
          description: Successful handling.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
        "401":
          description: Expired or malformed token.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
          
    Game:
      required:
        - question
        - answers
      properties:
        token:
          type: string
        question:
          type: object
          properties:
            id:
              type: string
            text:
              type: string
            extension:
              type: string
            
        answers:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              text:
                type: string
              extension:
                type: string

    Error:
      required:
        - code
        - message
      properties:
        message:
          type: string