apiVersion: v1
kind: Service
metadata:
  name: signing
spec:
  selector:
    app: signing
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: signing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signing
  template:
    metadata:
      labels:
        app: signing
    spec:
      containers:
      - name: signing
        image: cah-signing
        env:
        - name: FLASK_DEBUG
          value: "1"
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: config
              key: secret-key
        - name: TOKEN_TTL_HOURS
          valueFrom:
            configMapKeyRef:
              name: config
              key: token-ttl-hours
