openapi: 3.0.0
info:
  title: Signing Service
  version: 1.0.0
paths:
  /sign:
    post:
      description: Produce a JWT with the request body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../types.yaml#/components/schemas/Payload"
      responses:
        "200":
          description: Successful handling.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Token"
        "400":
          description: Malformed request.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "500":
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
  /verify:
    post:
      description: Verify that the given JWT is valid.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../types.yaml#/components/schemas/Token"
      responses:
        "200":
          description: Valid token.
        "400":
          description: Malformed request.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "401":
          description: Expired or malformed token.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
        "500":
          description: Internal error.
          content:
            application/json:
              schema:
                $ref: "../types.yaml#/components/schemas/Error"
